<?php
use Magento\Framework\App\Bootstrap;
require BP. '/app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);
$obj = $bootstrap->getObjectManager();
$state = $obj->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');

try
{
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
    $collection = $productCollection->addAttributeToSelect('*')
        ->load();
    $idArray = [];
    foreach ($collection as $product){
        $idArray[] =$product->getId();
    }
    $value = 10; //amount
    $productActionObject = $objectManager->create('Magento\Catalog\Model\Product\Action');
    $productActionObject->updateAttributes($idArray, array('cart_total_coast' => 200), 0);
    echo "OK!";

}
catch(\Exception $e)
{
    echo $e->getMessage();
    exit;
}
